### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Nguyen Van A",
  "email": "nguyenvana@gmail.com",
  "address": "123 VN",
  "dateOfBirth": "2002-05-16",
  "registeredDate": "2025-03-27"
}

###